; PlatformIO Project Configuration File

[core]
framework = arduino
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_compat_mode = strict
lib_deps = 
	ayushsharma82/ElegantOTA@^3.1.0
	ArduinoJson
	Adafruit NeoPixel
	adafruit/Adafruit MAX31855 library
	SPI
	https://github.com/adafruit/Adafruit_BusIO
	Wire
	; https://github.com/denyssene/SimpleKalmanFilter
	https://bitbucket.org/David_Such/nexgen_filter.git#1.0.2
	ayushsharma82/WebSerial
	adafruit/Adafruit SSD1306
	adafruit/Adafruit GFX Library
	https://github.com/sebnil/Moving-Avarage-Filter--Arduino-Library-
extra_scripts = pre:extra_scripts.py

[env:esp32-s3]
extends = core
; Directly pulls a specific stable pre-packaged release zip from pioarduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
board_build.filesystem = littlefs

; Serial Monitor & Upload Settings
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9
monitor_filters =
	esp32_exception_decoder

; Combined Build Flags
build_flags =
	${core.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D S3MINI=1

; Code Analysis and Checking
check_tool = clangtidy, cppcheck
check_skip_packages = yes
check_flags =
	clangtidy: --checks=-*,cert-*,clang-analyzer-* --fix
	cppcheck: --enable=all --std=c++11 --suppress=*:*/.pio/* --suppress=*:*/lib/* --suppress=missingIncludeSystem --suppress=unmatchedSuppression --suppress=missingInclude --suppress=unusedFunction
